### ISSUE TITLE
Empty Rows, no format choice

### ISSUE THREAD

**Issue by JariHanah** [xdev-software/vaadin-grid-exporter#161]
Hello, I just tested the addon, 
1 I get empty rows, 
2 does not read header if header contains components instead, 
3 and the dialog does not ask for a format, 

sample code of columns generated. 
```
Column<BasicDate> selectedColumn = addComponentColumn((source) -> {
            BasicDate item = source;
            BasicDate result = calsSelect.getValue().getDate(item.getDate());
            return generalRenderer.renderDate(result);

        }).setWidth("10px").setFlexGrow(1).setAutoWidth(true).setHeader(getT(cal.getName())+BasicCalendar.INFO_NAME);
        selectedColumn.setKey(KEY + ++count);//.setHeader(getT(b.getName() + BasicCalendar.INFO_SHORT));
        selectedColumn.setId(KEY + count);
```

Using Vaadin 24.3.3
![Screenshot 2024-01-18 215817](https://github.com/xdev-software/vaadin-grid-exporter/assets/71745537/eb2ab3c2-1508-410d-98bb-e622a0bb6b7a)
![Screenshot 2024-01-18 215756](https://github.com/xdev-software/vaadin-grid-exporter/assets/71745537/376c48c6-2052-4b39-a828-bc2e729b8e79)
![Screenshot 2024-01-18 215737](https://github.com/xdev-software/vaadin-grid-exporter/assets/71745537/9dc6596c-758c-40d7-a7ec-a258acfee8a2)

**Comment by AB-xdev** [comment]
Hi,

thank you for the issue.

Regarding your points:

> 1 I get empty rows,

This may be the case when you use very specific renderers. We can't e.g. export components that contain blobs like images.
Currently the following is supported:
* ValueProvider
* TextRenderer
* ColumnPathRenderer

This behavior can be overridden by extending ``GridDataExtractor`` and setting the supplier here:
https://github.com/xdev-software/vaadin-grid-exporter/blob/798f72f5de3f13869381b98a7094f4f333b422b6/vaadin-grid-exporter/src/main/java/software/xdev/vaadin/grid_exporter/GridExporter.java#L65

> 2 does not read header if header contains components instead,

The code how these values are extracted can be found here: 
https://github.com/xdev-software/vaadin-grid-exporter/blob/62e516688c1eec4a6a632b31ce04ba34cb9b5de8/vaadin-grid-exporter/src/main/java/software/xdev/vaadin/grid_exporter/column/headerresolving/VaadinColumnHeaderResolvingStrategy.java#L37-L45

Again as stated above if you use a very special component like e.g. an image this might not work.
You can however create a custom ``ColumnConfigurationBuilder`` that e.g. additional uses ``ColumnConfigurationHeaderResolvingStrategyBuilder#withManualColumnHeaderStrategy`` or something similar, to do the header-resolving yourself.

> 3 and the dialog does not ask for a format,

It should do that...
What version are you using exactly and what formats did you specify?

> sample code of columns generated.

Sorry but I can't quite read the code... Many important parts (what e.g. does method ``getT`` do or what is ``generalRenderer``?) are missing and it's not very well formatted either.

Feel free to pasted the complete code here :)

> Screenshots

The styling also looks wrong in the screenshots, maybe there is a problem with the Vaadin generated frontend?
Example:
![grafik](https://github.com/xdev-software/vaadin-grid-exporter/assets/45384811/a4a0933b-b5b1-4a8e-8104-6751e21e70a6)
should look more like this:
![grafik](https://github.com/xdev-software/vaadin-grid-exporter/assets/45384811/d0fd72b7-54b6-4e85-b99e-a83a46a266ff)

**Comment by AB-xdev** [comment]
Closing due to lack of feedback
