### ISSUE TITLE
Width of columns in Excel File

### ISSUE THREAD

**Issue by idonthaveusername9** [xdev-software/vaadin-grid-exporter#175]
Is it possible to set width of columns in excel file to fit content?
Or how can i set column width in excel file?

**Comment by AB-xdev** [comment]
Please consult the documentation of https://github.com/dynamicreports/dynamicreports (I wasn't able to find the wanted functionality quickly) or write your own Format as we did in the example [here](https://github.com/xdev-software/vaadin-grid-exporter/tree/develop/vaadin-grid-exporter-demo/src/main/java/software/xdev/vaadin/gridexport/example/jsonext).
