### ISSUE TITLE
Unable to show preview

### ISSUE THREAD

**Issue by idonthaveusername9** [xdev-software/vaadin-grid-exporter#176]
Unable to show preview, what might be a reason, what should i need to configure?
![image](https://github.com/xdev-software/vaadin-grid-exporter/assets/160304548/a5f828e2-2271-4621-8cd3-869c62a7dd2e)

**Comment by AB-xdev** [comment]
This is shown when the browser can't render/preview the content. E.g. when it's an excel file.
