### ISSUE TITLE
Update to JasperReports 7

### ISSUE THREAD

**Issue by JMMSW** [xdev-software/vaadin-grid-exporter#214]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/vaadin-grid-exporter/issues) or [closed](https://github.com/xdev-software/vaadin-grid-exporter/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request/enhancement.

### Description

JasperReports Library 7 is released:
https://github.com/TIBCOSoftware/jasperreports/releases/tag/7.0.0

Update Grid Exporter to this JasperReports version.

**Comment by AB-xdev** [comment]
Changelog: https://github.com/TIBCOSoftware/jasperreports/releases/tag/7.0.0

**Comment by AB-xdev** [comment]
Updated underlying lib: https://github.com/xdev-software/dynamicreports-core-for-grid-exporter

Todo: Update lib here and release

**Comment by AB-xdev** [comment]
Fixed with https://github.com/xdev-software/vaadin-grid-exporter/releases/tag/v3.1.0
