### ISSUE TITLE
Grid columns truncate data.

### ISSUE THREAD

**Issue by mcfar3199** [xdev-software/vaadin-grid-exporter#229]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/xdev-software/vaadin-grid-exporter/releases/latest)
- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/vaadin-grid-exporter/issues) or [closed](https://github.com/xdev-software/vaadin-grid-exporter/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

3.1.0

### Steps to reproduce the bug

1. Create a grid with 8-10 columns and text that is long or multiple words.
2. Try to export the grid in either pdf or .xlsx

### Expected behavior

I would expect the text to wrap in the cells the same way it does in the 3.0.3 release.

### Actual behavior

When the preview is shown the text is truncated in both the pdf and .xlsx formats. If you download the grid, the data is still missing.

**Comment by AB-xdev** [comment]
Can confirm the problem, looks like something was broken with Jasper 7

**Comment by AB-xdev** [comment]
So there is an error in the upstream dynamicreports where ``getTextFieldTextAdjust`` ALWAYS returns ``null``:
https://github.com/dynamicreports/dynamicreports/blob/3f80c6f7555a52761e751767783117fd5892a826/dynamicreports-core/src/main/java/net/sf/dynamicreports/report/defaults/Default.java#L1065

Before Jasper 7 this had no consequences as ``isTextFieldStretchWithOverflow`` hid this mistake, however this was removed in Jasper 7 and now the error occurs.

**Comment by AB-xdev** [comment]
Reported in original project: https://github.com/dynamicreports/dynamicreports/issues/180

**Comment by AB-xdev** [comment]
Should be fixed in v3.2.1 :)

**Comment by mcfar3199** [comment]
Thank you for your prompt response. You have built a much needed and awesome plugin!MitchSent from my iPhoneOn Jul 17, 2024, at 4:58 AM, Alex B ***@***.***> wrote:﻿
Should be fixed in v3.2.1 :)
