### ISSUE TITLE
PDF Export encoding

### ISSUE THREAD

**Issue by nero404** [xdev-software/vaadin-grid-exporter#237]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/vaadin-grid-exporter/issues) or [closed](https://github.com/xdev-software/vaadin-grid-exporter/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

Is there a simple way to change the encoding format in PDF export? Adding _EncodingConfigComponent_ to PdfFormat does not work.

Thanks for the answer.

**Comment by AB-xdev** [comment]
Currently there is no built-in way to do this as we never had this situation before.

AFAIK PDFs have no classic "encoding" as have text files: https://stackoverflow.com/a/42118616

According to the PDF spec [there can be certain string encodings](https://stackoverflow.com/a/10656899).

In JasperReports you can do it like [this](https://stackoverflow.com/questions/1886183/jasper-report-pdf-encoding), but it's recommended to use Fonts with the correct encoding instead.
