### ISSUE TITLE
The columns order are not taken into account

### ISSUE THREAD

**Issue by dt-sas** [xdev-software/vaadin-grid-exporter#256]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/xdev-software/vaadin-grid-exporter/releases/latest)
- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/vaadin-grid-exporter/issues) or [closed](https://github.com/xdev-software/vaadin-grid-exporter/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

3.2.1

### Steps to reproduce the bug

Hi,

With the latest version 3.2.1, the selected columns order are not taken into account.

Example:

I'm selecting this order from the first tab:

1. Name
2. Value
3. Category
4. Details

![1](https://github.com/user-attachments/assets/b31a2ee6-0ca1-4031-8b7c-1f55b91c4f64)
![2](https://github.com/user-attachments/assets/3df4c43e-f2af-447e-bd3d-f79ff4e3974c)
![3](https://github.com/user-attachments/assets/a4b84bc6-c23f-48f2-b07e-1849553baf8e)

And the preview shows this order (the default order of the grid):

1. Category
2. Name
3. Value
4. Details

**Comment by AB-xdev** [comment]
Can confirm the problem.

**Comment by AB-xdev** [comment]
Should be fixed in the next release :)
