### ISSUE TITLE
Exporting automatically without configuring the template

### ISSUE THREAD

**Issue by NicoDevX** [xdev-software/vaadin-grid-exporter#269]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/vaadin-grid-exporter/issues) or [closed](https://github.com/xdev-software/vaadin-grid-exporter/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

Hi is there an example of how to export a CSV with different templates?

I would like to have, that depending on the logged in user, a different csv format should be exported without opening the export dialog or with a preset  (depending on the user). But i cant find a way how to create a "template" with columns, separators etc wich i can use for the exporter.

**Comment by AB-xdev** [comment]
That's an interesting question, as the component was never designed for this.

I see the following possible options:
* You can use the corresponding format (e.g. CSVFormat) without the UI and fill it yourself with the required data. (Note that you have to create your own UI).
* or you can pre-configure the internal state (``GridExporterWizardState``) for your needs by creating a custom [``open`` method](https://github.com/xdev-software/vaadin-grid-exporter/blob/1ccae7a9f553ff6d37e8cbe55d0e718a295428c9/vaadin-grid-exporter/src/main/java/software/xdev/vaadin/grid_exporter/GridExporter.java#L155-L170).
  * Note however that this still shows the dialog with the selection steps.<br/>This could be worked around by creating a custom ``GridExporterWizard`` that doesn't adds the [``GeneralStep`` and ``FormatStep`` to the ``wizardPanel``](https://github.com/xdev-software/vaadin-grid-exporter/blob/ecc15274590781cd5953fd38bfdb31aa763ed11b/vaadin-grid-exporter/src/main/java/software/xdev/vaadin/grid_exporter/wizard/GridExporterWizard.java#L66-L67).

**Comment by AB-xdev** [comment]
Closing due to lack of response
