### ISSUE TITLE
Rework UI and functionality 

### ISSUE THREAD

**Issue by AB-xdev** [xdev-software/vaadin-grid-exporter#5]
The UI and functionality should be reworked.

* The project was originally developed with RapidClipse and through that contains a ton of auto-generated code that not very human-readable.
* The UI doesn't make any sense in some places and it's not very intuitive in the first place. Some kind of "assistant" would be nice:
Something like this maybe:
![grafik](https://user-images.githubusercontent.com/45384811/183047807-dd035944-539f-4eca-bc2f-247e9a3e2f49.png)

* Currently the same objects are used from the beginning to the end and are sometimes modified on the way. This is not a good practice as the code is not layered/isolated.

**Comment by AB-xdev** [comment]
The exports should also be refactored, the XLSX export should e.g. not be restrained to a page size or at least it should be configurable...

**Comment by JohannesRabauer** [comment]
Implemented the basic functionality on branch https://github.com/xdev-software/vaadin-grid-exporter/tree/refactoring. @AB-xdev please check if this according to our standards.
